buttons_text:
  view_vacancies: "Переглянути вакансії"
  add_parameters: "Додати параметри для пошуку"
  add_subscriptions: "Додати підписку"
  delete_parameters: "Видалити параметри"
  delete_subsriptions: "Видалити підписку"
  cancel: "Відмінити"
  whatever: "Та мені байдуже"
msg:
  start: "Привіт, я допоможу тобі знайти роботу твоєї мрії"
  undefined_command: "Я не знаю що ти від мене хочеш, я таке робити не вмію."
  main_menu: "Ти в головному меню"
  enter_postname: "Введи назву посади"
  undefined: "Я не знаю що ти від мене хочеш"
  wrong_sub_num: "Введено неправильний номер підписки"
  wrong_params_num: "Введено неправильний номер параметра"
  add_params_success: "Вітаю, параметри були успішно додані"
  empty_parameters: "Йойк, у тебе нема параметрів, додай їх будь ласка"
  enter_param_num: "Введи номер потрібного параметра\n\n"
  undefined_view: "Параметр видалений, це вже більше не працює"
  left_border: "Ти досяг лівої межі, рухайся вправо"
  right_border: "Ти досяг правої межі, рухайся вліво"
  delete_parameter_success: "Вибраний параметер успішно видалений"
  already_sub: "Ти вже підписаний на цей параметр, вибери якийсь інший"
  add_sub_success: "Чудово, тепер якщо з'являться нові вакансії для параметра, я тобі їх надішлю"
  empty_subs: "В тебе нема підписок, щоб щось видаляти"
  enter_subs_num: "Введи номер підписки, яку ти хочеш видалити\n\n"
  delete_sub_success: "Вибрана підписка успішно видалена"
  found_sub: "Я знайшов для тебе нові вакансії за твоїми підпискою \n %s: \n"
  cant_find_vacancies: "На жаль не вдалось знайти підходящі вакансії, спробуй інші параметри"
  enter_employment_type_num: "Тепер вибери номер виду зайнятості:\n"
  wrong_employment_type_num: "Ти ввів неправильний номер виду зайнятості"
  undefined_city: "Не вдалось знайти це місто в базі даних, спробуй щось інше"
  enter_city: "Введи назву міста"
